name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pyiceberg-kevinliu
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install poetry
        run: pip install poetry

      # - name: Set version
      #   run: python -m poetry version "${{ inputs.version }}"
      #   if: "${{ github.event.inputs.version != 'main' }}"

      # Publish the source distribution with the version that's in
      # the repository, otherwise the tests will fail
      - name: Compile source distribution
        run: python3 -m poetry build --format=sdist
        # if: startsWith(matrix.os, 'ubuntu')

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        with:
          output-dir: wheelhouse
          config-file: "pyproject.toml"
        env:
          # Ignore 32 bit architectures
          CIBW_ARCHS: "auto64"
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.8,<3.12"
          CIBW_TEST_REQUIRES: "pytest==7.4.2 moto==5.0.1"
          CIBW_TEST_EXTRAS: "s3fs,glue"
          # CIBW_TEST_COMMAND: "pytest {project}/tests/avro/test_decoder.py"
          # There is an upstream issue with installing on MacOSX
          # https://github.com/pypa/cibuildwheel/issues/1603
          # Ignore tests for pypy since not all dependencies are compiled for it
          # and would require a local rust build chain
          CIBW_TEST_SKIP: "pp* *macosx*"

      # - name: Add source distribution
      #   if: startsWith(matrix.os, 'ubuntu')
      #   run: ls -lah dist/* && cp dist/* wheelhouse/

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: "release-${{ github.event.inputs.version }}"
      #     path: ./wheelhouse/*

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
